### ISSUE TITLE
Error while saving package

### ISSUE THREAD

**Issue by draculaisms** [Zerbu/Mod-Constructor-5#15]
Got this error while trying to save a .package file on Mod Constructor V5.

![image](https://user-images.githubusercontent.com/100455903/155827382-6705e798-ad4f-471b-9a31-3f47bb8b3f74.png)

"The system cannot find the file specified

   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Constructor5.Base.Export.Exporter.RunPythonScript(String fileName)
   at Constructor5.Base.Export.Exporter.Export()
   at Constructor5.UI.Main.ExportCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

Any idea what this means?

**Comment by Zerbu** [comment]
Judging from the message, it sounds like Python 2.7 isn't installed (although this is still a bug as it should have shown a custom error, so I'll look into that). There should be a prompt asking you to install Python when you launch the program. Installing it _should_ solve the problem (as for the vague error message, I've added it to my todo list to fix in the next update).

**Comment by draculaisms** [comment]
> Judging from the message, it sounds like Python 3.7 isn't installed (although this is still a bug as it should have shown a custom error, so I'll look into that). There should be a prompt asking you to install Python when you launch the program. Installing it _should_ solve the problem (as for the vague error message, I've added it to my todo list to fix in the next update).

Is it definitely a python issue? I have python installed and I've used it with previous versions of the alpha & constructor. I also have an exported .py file for the aspiration in particular I am working on. I can try uninstalling and reinstalling python maybe?

**Comment by BosseladyTV** [comment]
I'm getting this message as well. And I'm pretty sure Python 3.7 is installed, but I'll check.

**Comment by BosseladyTV** [comment]
> I'm getting this message as well. And I'm pretty sure Python 3.7 is installed, but I'll check.

Ok, I did have Python installed. So I chose the "Repair" option, and then tried exporting my mod, and it worked. Just FYI in case it helps! Thx

**Comment by Zerbu** [comment]
Glad to hear you got it fixed!
I assume the same will work for draculaisms, but I'll leave this issue open for a little bit longer just in case it doesn't.

**Comment by BosseladyTV** [comment]
Thank you!
