### ISSUE TITLE
Small mod is too big for SimData?

### ISSUE THREAD

**Issue by ShadowDeveloper** [Zerbu/Mod-Constructor-5#153]
I'm making a simple mod, pretty small, just a couple of wants, an aspiration, some buffs, and some traits.
And yet I get a lovely error when trying to export this (as far as I know) small mod.

Is my mod really that big, or is this just a bug?

![Mod details](https://github.com/Zerbu/Mod-Constructor-5/assets/74436506/02052028-08b2-4d98-89b0-0381203f6a96)

![Error](https://github.com/Zerbu/Mod-Constructor-5/assets/74436506/1b774bd4-b518-4cae-a8f7-b5d160bad14d)

Full error:
List exceeds the maximum amount allowed by the SimData

   at Constructor5.Base.ExportSystem.Tuning.SimData.SimDataHandler.WriteList(Int32 startPosition, IEnumerable`1 items, Int32 maxSize, Boolean zerofillExtra, Int32 extraSpace)
   at Constructor5.Elements.ObjectiveSets.ObjectiveSet.BuildSimData(TuningHeader tuning)
   at Constructor5.Elements.ObjectiveSets.ObjectiveSet.Constructor5.Base.Export.IExportableElement.OnExport()
   at Constructor5.Base.ExportSystem.Exporter.ExportElements()
   at Constructor5.Base.ExportSystem.Exporter.Export()
   at Constructor5.UI.Main.ExportCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ShadowDeveloper** [comment]
Too many objectives in my aspiration!
