### ISSUE TITLE
Error message when exporting

### ISSUE THREAD

**Issue by k-daisy** [Zerbu/Mod-Constructor-5#182]
Hello, I am new to using the Mod constructor, but I have tried to make a career for the Sims 4. However, when I export it, it tells me there is an error as:

"List exceeds the maximum amount allowed by the SimData

   at Constructor5.Base.ExportSystem.Tuning.SimData.SimDataHandler.WriteList(Int32 startPosition, IEnumerable`1 items, Int32 maxSize, Boolean zerofillExtra, Int32 extraSpace)
   at Constructor5.Elements.ObjectiveSets.ObjectiveSet.BuildSimDataCareer(TuningHeader tuning)
   at Constructor5.Elements.ObjectiveSets.ObjectiveSet.Constructor5.Base.Export.IExportableElement.OnExport()
   at Constructor5.Base.ExportSystem.Exporter.ExportElements()
   at Constructor5.Base.ExportSystem.Exporter.Export()
   at Constructor5.UI.Main.ExportCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

So I am unsure what I have done wrong or if this is a bug? Please advise, thank you very much.

**Comment by Saengdune** [comment]
Hey did you ever get it to work? I have the same issue. My earlier, unfurnished version was fine but now I have this problem.

**Comment by k-daisy** [comment]
> Hey did you ever get it to work? I have the same issue. My earlier, unfurnished version was fine but now I have this problem.

I managed to get it to work by trying again with a new career but without the branches by just adding the 10 levels and then editing the names and text. But could not get it to work with multiple branches sadly

**Comment by Saengdune** [comment]
> > Hey did you ever get it to work? I have the same issue. My earlier, unfurnished version was fine but now I have this problem.
> 
> I managed to get it to work by trying again with a new career but without the branches by just adding the 10 levels and then editing the names and text. But could not get it to work with multiple branches sadly

Nooo that’s so disappointing. At least it sorta worked in the end. Thank you!
