### ISSUE TITLE
Can't open mod constructor

### ISSUE THREAD

**Issue by Minniestroni** [Zerbu/Mod-Constructor-5#192]
When I open it from task bar it comes up with the robot thing that I assume is the loading screen, the displays an error message reading

Mod constructor has encountered an unexpected error
Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at Constructor5.UI.Launcher.LauncherWindow..ctor()
   at Constructor5.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

A similar error message was displayed previously when trying to search for an object to link a new super interaction to, which is why I closed the application in the first place.

**Comment by suekellyerin-glitch** [comment]
I've had this issue too.
