### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Morgaine2005** [Zerbu/Mod-Constructor-5#50]
Whenever I try to export the aspiration I'm creating, I get this error:

Object reference not set to an instance of an object.

   at Constructor5.Base.ExportSystem.Tuning.TuningBase.Set[T](String name, Object value)
   at Constructor5.TestConditionTypes.Compound.CompoundCondition.OnExportVariant(TunableBase variantTunable)
   at Constructor5.Elements.TestConditions.TestConditionTuning.TuneTestList(TuningBase tuning, IEnumerable`1 conditions, String tunableName)
   at Constructor5.Elements.LootActionSets.LootActionSet.ExportConditionGroup(LASConditionGroup group, LASExportContext originalContext)
   at Constructor5.Elements.LootActionSets.LootActionSet.Constructor5.Base.Export.IExportableElement.OnExport()
   at Constructor5.Base.ExportSystem.Exporter.ExportElements()
   at Constructor5.Base.ExportSystem.Exporter.Export()
   at Constructor5.UI.Main.ExportCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I have combed through my aspiration for errors and can't find anything missing. I was able to export it last night. I've undone most/all of the changes I did today in an attempt to get it to export, but no luck.

Furthermore, in my attempts to figure this out, I've noticed the following:

1. The Trait Origin box (for the reward trait) won't stay filled in. If I close the program and open it again, the text I had in there is gone.
2. Many of my compound conditions seemed to disappear between then I closed the program last night and opened it today. I can understand missing one or two compound conditions (it's a complex reward trait), but I specifically remember creating some of the ones yesterday that were gone today.

Any help would be appreciated. I'm at my wit's end.

**Comment by Morgaine2005** [comment]
Just want to report back with more findings. I restarted work on my mod, exporting at regular intervals to make sure it was working. Everything worked smoothly UNTIL I went to close the program for the night. I exported right before I closed and it worked perfectly. Closed the program, opened it again, and tried to export. (Only change I made was adding the text back to the Trait Origin box.) Got the object reference error. Closed the program, opened it, tried to export one more time making no changes (the Trait Origin Box had erased itself again). Got the object reference error.

Please let me know if you need me to provide any kind of files or further info for you to look at. Thank you!

**Comment by Zerbu** [comment]
This happens when you have a context-specific compound condition that doesn't have any "or" conditions. It should be fixed in the next update, as well as the trait origin issue :)

**Comment by Morgaine2005** [comment]
Thank you very much!
    On Saturday, October 22, 2022 at 05:55:45 PM EDT, Zerbu ***@***.***> wrote:  
 
 


This happens when you have a context-specific compound condition that doesn't have any "or" conditions. It should be fixed in the next update, as well as the trait origin issue :)
